### ISSUE TITLE
Implement the `core.CRMBase` model

### ISSUE THREAD

**Issue by eronlloyd** [democracrm/democracrm#34]
## Description
The `core.CRMBase` model implements a base class for all models in the platform, providing the basic functionality we can expect all objects to possess. As the platform evolves, new functionality can be added here to all existing objects.

## Requirements
- Inherits from `django.db.models.Model` (this will change again once GeoDjango is integrated)
- A non-primary key UUID for global referencing and external system roundtripping
- A timestamp when the object is created
- A timestamp when the object is updated
- The user account that created the object
- The user account that updated the object

## Dependencies
- None

## Tasks
- [ ] Write unit tests
- [ ] Write functional tests
- [ ] Write docstring
- [ ] Write code
- [ ] Write wiki page
