### ISSUE TITLE
Implement the `core.ContactRole` model

### ISSUE THREAD

**Issue by eronlloyd** [democracrm/democracrm#35]
## Requirements
- 

## Dependencies
- None

## Tasks
- [ ] Write unit tests
- [ ] Write functional tests
- [ ] Write docstring
- [ ] Write code
- [ ] Write wiki page
